### ISSUE TITLE
SDK samples are outdated 

### ISSUE THREAD

**Issue by dcanonmolina** [twilio/twilio-go#104]
Hello!

SDK samples in https://www.twilio.com/docs/libraries/go are outdated. They point out to `github.com/twilio/twilio-go/twilio `reference, but the Twilio folder was removed since v0.8.0. Would it be possible to update these samples? Thanks!

**Comment by eshanholtz** [comment]
Hi @dcanonmolina 

I've passed along the feedback to our docs team and they're going to work on updating the samples on that page! In the meantime, the documentation in our [README](https://github.com/twilio/twilio-go#documentation) is up-to-date. 

I'm going to go ahead and close this issue as the docs update is not a change that can be made in this repository.
