### ISSUE TITLE
Double check the usability on the README

### ISSUE THREAD

**Issue by kevinburke** [twilio/twilio-go#107]
It's weird that the example for creating a message requires JSON marshaling of the response (??), but the example for creating a call does not.

Also, not an expert but guessing that the message/call examples are going to be relevant to a lot more people than the info on how to set the region or edge, and should maybe go higher up on the page.

Also I guess it's bizarre that errors are being printed and then ignored.

**Comment by shwetha-manvinkurke** [comment]
Hi @kevinburke These are merely examples that show you what you could do with the `response/error` but there is always room for improvement. Setting `edge/region` should happen at the client initialization and hence it makes to specify that in the examples before any call is made. You are also welcome to suggest any improvements by submitting a PR.
