### ISSUE TITLE
MediaExternalLocation is missing in CompositionV1

### ISSUE THREAD

**Issue by jlpedrosa** [twilio/twilio-go#128]
### Issue Summary
The struct CompositionV1 is missing field: `MediaExternalLocation` 
this field is not in the schema:  schema issue: https://github.com/twilio/twilio-oai/issues/48

### Steps to Reproduce
Schema issue, can't be reproduced.

### Code Snippet
```go
# paste code here
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-go version: 
* go version:

**Comment by shwetha-manvinkurke** [comment]
Where in the docs do you see that field should be present? It's a private field that shouldn't be exposed yet.

**Comment by eshanholtz** [comment]
Closing due to lack of customer response.
