### ISSUE TITLE
TwiML Reponse API

### ISSUE THREAD

**Issue by f1rstmehul** [twilio/twilio-go#136]
It would be nice if ***twilio-go*** provides an API to generate a [TwiML response](https://www.twilio.com/docs/voice/twiml). Almost all Twilio's Server-side Helper Libraries provide an API to do so. although I can use [encoding/xml](https://pkg.go.dev/encoding/xml) to generate TwiML response.

**Comment by shwetha-manvinkurke** [comment]
@astroparam We have the work defined for this in our backlog and will be working on it in the near future.

**Comment by mztnnrt** [comment]
now we use https://github.com/homie-dev/gotwiml, 
but, if possible we want to use provided from https://github.com/twilio/twilio-go

**Comment by stevennic-twilio** [comment]
Hi @f1rstmehul and @mztnnrt

I just wanted to follow-up with both of you to let you know that TwiML generation was released in [v1.0.0-rc.8](https://github.com/twilio/twilio-go/releases/tag/v1.0.0-rc.8). All current, non-beta versions of the SDK will have this available as well (at the time of writing [v1.3.0](https://github.com/twilio/twilio-go/releases/tag/v1.3.0) is the latest build).

Some documentation on how to implement [can be found here](https://github.com/twilio/twilio-go#generating-twiml).
