### ISSUE TITLE
Panic in BuildUrl - error is not handled

### ISSUE THREAD

**Issue by kpritam** [twilio/twilio-go#141]
We are seeing panics in our application.

While investigating, I figured out that `BuildUrl` function is ignoring error which is causing panic later in the flow.

This happens when you have wrong `ServiceSid` configured.

https://github.com/twilio/twilio-go/blob/main/client/request_handler.go#L32

**Comment by JenniferMah** [comment]
Hi @kpritam! Thanks for submitting a PR. It is currently in our team's review backlog.
