### ISSUE TITLE
Unable to set otp code length

### ISSUE THREAD

**Issue by venu-prasanna-tw** [twilio/twilio-go#145]
### Issue Summary
I am using https://github.com/twilio/twilio-go/tree/main/rest/verify/v2 library to send OTP code.
But I wanted to change the OTP code length and I don't see any option in CreateMessage that will accept the OtpCode length.

### Technical details:
* twilio-go version: verify v2
* go version: go1.17.6

**Comment by childish-sambino** [comment]
This is not a change that can be made in the library. Please [file a support ticket](https://twilio.com/help/contact) to inquire about adding this feature to the API.

**Comment by kpritam** [comment]
Hi @childish-sambino , as per the API defined here https://www.twilio.com/docs/verify/api/service#create-a-verification-service, verify service do support `CodeLength` parameter.
I can even see `CodeLength` option available in `verify.V2.CreateServiceParams` but none of the public facing API supports this.

**Comment by childish-sambino** [comment]
@kpritam Ah. I see that code length is available when creating the service but not when creating the message. This param is mentioned in the docs you link and as part of the create service params. What docs do you think are needed?

**Comment by venu-prasanna-tw** [comment]
I have two following questions:
1. Is there any docs that would guide us to set the code length when sending OTP using verify.CreateVerificationParams{} (using verifyV2)?
2. Is there any docs that would help us in utilising the verify.V2.CreateServiceParams ?

**Comment by childish-sambino** [comment]
1. Yes
2. No, the API does not support this.
3. No, but here's an example:
```go
import (
	"fmt"
	"github.com/twilio/twilio-go"
	verify "github.com/twilio/twilio-go/rest/verify/v2"
)

func main() {
	twilioClient := twilio.NewRestClient()

	verifyServiceParams := &verify.CreateServiceParams{}
	verifyServiceParams.SetFriendlyName("Service with Code Length 10")
	verifyServiceParams.SetCodeLength(10)

	resp, err := twilioClient.VerifyV2.CreateService(verifyServiceParams)
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(*resp.Sid)
	}
}
```
