### ISSUE TITLE
changing base API url

### ISSUE THREAD

**Issue by omertoast** [twilio/twilio-go#170]
I have to change the base API url in order to send requests to the mock server in tests but apparently, API URLs are hardcoded so I couldn't find a way to send requests to the mock server.

**Comment by omertoast** [comment]
i fixed this by using custom clients.

**Comment by arthurvaverko** [comment]
@omertoast can you share the implementation ? I'm at the exact same situation ..
should i just copy the client form sdk's source and allow reconfigure the url for each API ?

**Comment by omertoast** [comment]
It's been a while since I did this, so I have no idea sorry.
