### ISSUE TITLE
MockBaseClient broken by 1.20.0 update which changed the function signature of SendRequest

### ISSUE THREAD

**Issue by saurori** [twilio/twilio-go#244]
### Issue Summary
Version `1.20.0` changed the BaseClient SendRequest method (seen in [this pull request](https://github.com/twilio/twilio-go/pull/239/files#diff-32f833e7c3e5c091b1b1acc9b4a06096ebc8fca31cb5be6b4d5dbd7e9ee3f896R13)) to add `body ...byte` as a function parameter. The corresponding [MockBaseClient](https://github.com/twilio/twilio-go/blob/v1.20.1/client/mock_client.go#L63) was not updated.

### Steps to Reproduce
1. Use `twilio-go` version `1.20.1`
2. Attempt to use a MockBaseClient (see code below)

### Code Snippet
```go
ctrl := gomock.NewController(t)
c := client.NewMockBaseClient(ctrl)
twilioClient := twilio.NewRestClientWithParams(twilio.ClientParams{Client: c})
```

### Exception/Log
```
cannot use c (variable of type *client.MockBaseClient) as client.BaseClient value in struct literal: *client.MockBaseClient does not implement client.BaseClient (wrong type for method SendRequest)
		have SendRequest(string, string, url.Values, map[string]interface{}) (*http.Response, error)
		want SendRequest(string, string, url.Values, map[string]interface{}, ...byte) (*http.Response, error)compiler[InvalidIfaceAssign](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#InvalidIfaceAssign)
```

### Technical details:
* twilio-go version: `1.20.1`
* go version: `go version go1.22.2 darwin/arm64`

**Comment by sbansla** [comment]
Let me take a look into this.

**Comment by tiwarishubham635** [comment]
Hey @saurori!
I have created a PR #246 for this. Please check.
Thanks!
