### ISSUE TITLE
400 when creating Studio Flow executions

### ISSUE THREAD

**Issue by fterrag** [twilio/twilio-go#250]
Hi there,

Since upgrading to 1.22.0, we're not able to create Studio Flow executions: Status: 400 - ApiError 20001: Missing required parameter To in the post body (null) More info: https://www.twilio.com/docs/errors/20001

We're including a value for the To param in the request:
```go
params := &twiliostudio.CreateExecutionParams{}
params.SetTo(to.String())
```

Any idea what might be causing this?

**Comment by kevinburkesegment** [comment]
Hi @fterrag, v1.22.0 had an issue and has since been retracted. Please downgrade or upgrade to v1.22.2, and then report back if you still have a problem. Thanks!
